version: '3.8'
services:
  clientes:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /home/rene/Documents/app/clientes:/app/clientes

  servicios:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - /home/rene/Documents/app/clientes:/app/clientes
    command: ["python", "servicio.py"]

  almacenamiento:
    build: .
    ports:
      - "5002:5002"
    volumes:
      - /home/rene/Documents/app/backups:/app/backups
    command: ["python", "almacenamiento.py"]
